// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWjEX1evoNZV71wnVm8-aUtbMoEucrXM',
    appId: '1:559394641703:web:08d1e1fabce4f946847b02',
    messagingSenderId: '559394641703',
    projectId: 'dharani-cotton-mill',
    authDomain: 'dharani-cotton-mill.firebaseapp.com',
    storageBucket: 'dharani-cotton-mill.firebasestorage.app',
    measurementId: 'G-Q6ZVRJ9F7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7tGKiLNLZ_uzR7yXn9o_Yf5ywXp7DcM',
    appId: '1:559394641703:android:2a3b7b3fd75ac47f847b02',
    messagingSenderId: '559394641703',
    projectId: 'dharani-cotton-mill',
    storageBucket: 'dharani-cotton-mill.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABpLy7HWM3-1rEqHEJf_44nX-1CurmQTw',
    appId: '1:559394641703:ios:e3e57bc9736eb133847b02',
    messagingSenderId: '559394641703',
    projectId: 'dharani-cotton-mill',
    storageBucket: 'dharani-cotton-mill.firebasestorage.app',
    iosBundleId: 'com.example.dharaniSalaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABpLy7HWM3-1rEqHEJf_44nX-1CurmQTw',
    appId: '1:559394641703:ios:e3e57bc9736eb133847b02',
    messagingSenderId: '559394641703',
    projectId: 'dharani-cotton-mill',
    storageBucket: 'dharani-cotton-mill.firebasestorage.app',
    iosBundleId: 'com.example.dharaniSalaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAWjEX1evoNZV71wnVm8-aUtbMoEucrXM',
    appId: '1:559394641703:web:4ca12d086ecd0ded847b02',
    messagingSenderId: '559394641703',
    projectId: 'dharani-cotton-mill',
    authDomain: 'dharani-cotton-mill.firebaseapp.com',
    storageBucket: 'dharani-cotton-mill.firebasestorage.app',
    measurementId: 'G-SJL6HSG46Q',
  );
}
